
name: Build

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake

      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Executables
      run: |
        ${{github.workspace}}\build\benchmark\Debug\benchmark_counter.exe
        ${{github.workspace}}\build\verify\Debug\verify_counter.exe

